name: 'Terrascan'

on:
  push:
   branches: master
   
jobs:     
  terrascan:
     name: 'terrascan'
     runs-on: ubuntu-latest
     steps: 
       - name: Checkout
         uses: actions/checkout@v2
       - name: 'Run Terrascan'
         run: |
           git clone https://github.com/accurics/terrascan.git
           ls 
           pwd 
           cp "east/how to create ec2 instance/*.tf" terrascan
           cd terrascan
           make build 
           ./bin/terrascan
           ./bin/terrascan scan -t aws
